name: Build and Deploy Demo
on:
  push: 
    branches:   
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: |
         npm install -g @angular/cli
         npm install
         ng build ngx-monetization --prod
         ng build e2e-app --prod --base-href="/ngx-monetization/"
    - uses: JamesIves/github-pages-deploy-action@releases/v2
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BASE_BRANCH: master
        BRANCH: master
        FOLDER: dist/e2e-app
